/*REMOVE ESPAÇO DO INÍCIO*/
SELECT LTRIM('    OLÁ') AS RESULTADO;

/*REMOVE ESPAÇO DO FINAL*/
SELECT RTRIM('OLÁ     ') AS RESULTADO;

SELECT TRIM('    OLÁ     ') AS RESULTADO;

SELECT CONCAT('OLÁ', ' ', 'TUDO BEM', '?') AS RESULTADO;

SELECT UPPER('olá, tudo bem?') AS RESULTADO;

SELECT LOWER('OLÁ, TUDO BEM?') AS RESULTADO;

SELECT SUBSTRING('OLÁ, TUDO BEM?', 5) AS RESULTADO;



SELECT SUBSTRING('OLÁ, TUDO BEM?', 5, 4) AS RESULTADO;

SELECT CONCAT(NOME, ' (', CPF, ')') AS RESULTADO FROM tabela_de_clientes; 